import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LangParams {
  lang: string;
}

// Assurez-vous que cette fonction retourne des paramètres valides
export async function generateStaticParams() {
  return [
    { lang: "en" },
    { lang: "zh" }
  ];
}

// Mettez à jour la signature de la fonction pour le type `LayoutProps` correct
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  params: LangParams; // Assurez-vous que params correspond à LangParams
}) {

  return (
    <html suppressHydrationWarning={true}>
      <body className={inter.className} data-cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
