import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Fonction pour générer les paramètres statiques
export async function generateStaticParams() {
  return [
    { lang: "en" },
    { lang: "zh" },
  ];
}

// Mise à jour de la fonction RootLayout en utilisant params
export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string }; // Assurez-vous que le type est correct
}) {
  // Utilisez params si nécessaire
  console.log(`Langue actuelle: ${params.lang}`);

  return (
    <html suppressHydrationWarning={true}>
      <body className={inter.className} data-cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
