import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Mise à jour de la fonction RootLayout en utilisant params
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html suppressHydrationWarning={true}>
      <head>
        <link rel="icon" href="/images/logo.webp" />
      </head>
      <body className={inter.className} data-cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
